version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hello-app

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root